FROM kong:3.7
USER root
RUN mkdir -p /kong && chown kong:kong /kong
COPY --chown=kong:kong kong.yml /kong/kong.yml
USER kong
ENV KONG_DATABASE=off \
    KONG_DECLARATIVE_CONFIG=/kong/kong.yml \
    KONG_PROXY_LISTEN=0.0.0.0:8000 \
    KONG_ADMIN_LISTEN=127.0.0.1:8001 \
    KONG_PROXY_ACCESS_LOG=/dev/stdout \
    KONG_PROXY_ERROR_LOG=/dev/stderr
